apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: auction-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: auction-app
  minReplicas: 1
  maxReplicas: 10
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 2
    scaleUp:
        stabilizationWindowSeconds: 1
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Value
          value: 5Mi
          averageValue: 5Mi
